### ISSUE TITLE
Not working with A-Frame 1.0.3

### ISSUE THREAD

**Issue by planetvoodoo** [harlyq/aframe-spe-particles-component#2]
Been waiting for someone else to notice for a few weeks. This no longer works with latest release of A-Frame 1.0.3 - any idea why?

**Comment by harlyq** [comment]
I tried bumping the aframe reference in index.html to 1.0.3, and it continued to work with Chrome, Firefox and Edge (on PC).  There was an error in index.html with aframe-animation-component.min.js (because the animation component it is now included in aframe 1.0.0), and there were some warnings about .addAttribute and .dynamic from aframe-spe-particles-component.js but the particles still appeared correctly.

Do you have a specific console error? Which platform was the code not working on?

**Comment by stemkoski** [comment]
I can confirm the spe-particles-component is working fine with A-Frame 1.0.4.

Working demo: see
https://stemkoski.github.io/A-Frame-Examples/particles.html
Source:
https://github.com/stemkoski/A-Frame-Examples/blob/master/particles.html

Recommending that this issue be closed.

**Comment by planetvoodoo** [comment]
Aww man! I totally missed the email all those months ago, sorry for the late reply @harlyq. It was giving me problems on one of my sites https://voodoopeople.com - so I used an older version of A-Frame in the end. Will have a play with it again and see what happens. @stemkoski Will also check out your demo now! Saw a quick image on Twitter, pretty colors! Got me all excited. Thanks for getting back to me, and keep up the good work guys.
